name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: API Tests (Vitest + Allure)
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
  
      - name: Install dependencies (API)
        working-directory: apps/api
        run: npm install
  
      - name: Run API tests (Allure)
        working-directory: apps/api
        run: npm run test:allure
  
      - name: Upload Allure report (API)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-api
          path: apps/api/allure-report
  
      - name: Upload Allure results (API raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: apps/api/allure-results  

  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: api-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Install root dependencies
        run: npm install

      - name: Install dependencies (API)
        working-directory: apps/api
        run: npm install

      - name: Install dependencies (Web)
        working-directory: apps/web
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run e2e

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Playwright test results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results
